blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/fenykepesz/expense-dashboard/discussions
    about: For general questions, use GitHub Discussions
